name: CI - Build on PR

on:
  pull_request:
    branches: ["**"]

permissions:
  contents: read

concurrency:
  group: pr-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install deps
        run: npm ci

      - name: Build (capture log)
        env:
          NEXT_TELEMETRY_DISABLED: "1"
          CI: "true"
        run: |
          set -o pipefail
          npm run build 2>&1 | tee build.log

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
